<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<NoWarn>1701;1702;1591</NoWarn>
		<DocumentationFile>MiRomWeb.Web.Core.xml</DocumentationFile>
	</PropertyGroup>


	<ItemGroup>
		<None Remove="MiRomWeb.Web.Core.xml" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MiRomWeb.Application\MiRomWeb.Application.csproj" />
	</ItemGroup>

</Project>
